# Generated by Django 4.1.7 on 2023-02-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_sub_subcategory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hy',
            field=models.CharField(max_length=30, null=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='SubCategory name'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_hy',
            field=models.CharField(max_length=30, null=True, verbose_name='SubCategory name'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='SubCategory name'),
        ),
    ]
