# Generated by Django 4.1.7 on 2023-02-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_forzhenya'),
    ]

    operations = [
        migrations.AddField(
            model_name='forzhenya',
            name='name_en',
            field=models.CharField(max_length=40, null=True, verbose_name='ForZhenya'),
        ),
        migrations.AddField(
            model_name='forzhenya',
            name='name_hy',
            field=models.CharField(max_length=40, null=True, verbose_name='ForZhenya'),
        ),
        migrations.AddField(
            model_name='forzhenya',
            name='name_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='ForZhenya'),
        ),
    ]
