# Generated by Django 4.1.7 on 2023-03-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_forzhenya_name_en_forzhenya_name_hy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_of_money',
            field=models.CharField(choices=[('RUB', 'Russian'), ('ARM', 'Armenian'), ('USD', 'American')], default=1, max_length=60, verbose_name='Type price name'),
            preserve_default=False,
        ),
    ]
