# Generated by Django 4.1.7 on 2023-03-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_product_type_of_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_hy',
            field=models.CharField(max_length=30, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_en',
            field=models.IntegerField(null=True, verbose_name='Product price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_hy',
            field=models.IntegerField(null=True, verbose_name='Product price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_ru',
            field=models.IntegerField(null=True, verbose_name='Product price'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_of_money_en',
            field=models.CharField(choices=[('RUB', 'Russian'), ('ARM', 'Armenian'), ('USD', 'American')], max_length=60, null=True, verbose_name='Type price name'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_of_money_hy',
            field=models.CharField(choices=[('RUB', 'Russian'), ('ARM', 'Armenian'), ('USD', 'American')], max_length=60, null=True, verbose_name='Type price name'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_of_money_ru',
            field=models.CharField(choices=[('RUB', 'Russian'), ('ARM', 'Armenian'), ('USD', 'American')], max_length=60, null=True, verbose_name='Type price name'),
        ),
    ]
